server:
  port: 9002
spring:
  application:
    name: basic-server
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: dev
        file-extension: yaml
        refresh-enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/music_basic?useServerPrepStmts=true&cachePrepStmts=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: '123456'
      minimum-idle: 5
      maximum-pool-size: 30
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCp
      max-lifetime: 1800000
      connection-timeout: 30000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migration

